### ISSUE TITLE
Php 7.2 Updates

### ISSUE THREAD

**Issue by jasonw4331** [pmt-mcpe-fun/PocketMineServerManager#1]
### PocketMine-MP from pmmp is now running on php 7.2
This software is no longer compatible as an installer due to the fact that it doesn't install the correct binaries

### OS:

N/A

### PHP Version:

N/A
    
    
### Steps to reproduce:

1. N/A
2. ...
3. ...

**Comment by Ad5001** [comment]
I'll make an update with auto compiling binaries when i'll have an sh for Windows.
