### ISSUE TITLE
No apk

### ISSUE THREAD

**Issue by TiesGamesNL** [pmt-mcpe-fun/PocketMineServerManager#10]
## Description:    

There isnt any apk download
    

### PHP Version:

7.0.3
    
    
### Steps to reproduce:

1. When i click download apk it says something like "not found on this server"
2. thats wierd 
3. ...

**Comment by ghost** [comment]
This is a problem with is, as our base ("Electron") does not support Android in any way. We reccomend that you check out PocketServer on the play store.
