### ISSUE TITLE
The "version list" does not appear on windows builds.

### ISSUE THREAD

**Issue by ghost** [pmt-mcpe-fun/PocketMineServerManager#11]
## Description:    

The issue seems to be that when creating a server, the versions do not seem to show. I recommend https://pocketmine-versions.glitch.me/alpha or https://pocketmine-versions.glitch.me/development (it is a service that provides the data for official releases of pmmp/PocketMine-MP on Jenkins.

### OS:

Windows

### PHP Version:

7.0.3
    
    
### Steps to reproduce:

1. Attempt to create a brand new server
2. Select the version dropdown box

### Media
![email screenshot](https://camo.githubusercontent.com/1807bdc67f064d8d7e3ac8c6ce37fa6eeef17357/68747470733a2f2f756361726563646e2e636f6d2f61386236323431362d646564312d343732622d386633362d3338326331633235383832392f)

### Extra Information
**Reporter:** Chingiz Mustafayav
**Origin:** support@mcpe.fun

**Comment by Ad5001** [comment]
This bug occurs while PSM is loading servers versions from the list online and that's not completly loaded, but you click on create server.

**Comment by samuelctn** [comment]
http://prntscr.com/ke30d0

**Comment by Ad5001** [comment]
Close the dialog box and reopen it. It should appear afterwards.

**Comment by samuelctn** [comment]
http://prntscr.com/kec2zx

**Comment by Ad5001** [comment]
Ok check into your home folder/.pocketmine/php/bin/php7/bin/php If it doesn't exist, close the app, delete your .pocketmine folder, and relaunch the app.

**Comment by samuelctn** [comment]
still not working man. make a video / tutorial for everyone
