### ISSUE TITLE
Download link not working [Device: Unknown]

### ISSUE THREAD

**Issue by samuelctn** [pmt-mcpe-fun/PocketMineServerManager#12]
_download link doesnt work_

**Comment by Ad5001** [comment]
What do you mean?

**Comment by samuelctn** [comment]
http://prntscr.com/kdebpg

**Comment by Ad5001** [comment]
Oh ok. Wait a few minutes. I'll resolve this

**Comment by Ad5001** [comment]
Should be fixed now.

**Comment by samuelctn** [comment]
still doesnt works

**Comment by Ad5001** [comment]
Well, it's just me that wasn't paying enough attention on the windows binary I transfered. You should be able to download it now.

**Comment by samuelctn** [comment]
working thanks
