### ISSUE TITLE
Problem accessing /job/PocketMine-MP/315/artifact/PocketMine-MP_1.6.2dev-315_8274f5b3_API-3.0.0-ALPHA7.phar

### ISSUE THREAD

**Issue by r7vmc** [pmt-mcpe-fun/PocketMineServerManager#2]
## Description:    

when i start the server i got this error:

<pre>[PMS] Starting server PMMP...
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /job/PocketMine-MP/315/artifact/PocketMine-MP_1.6.2dev-315_8274f5b3_API-3.0.0-ALPHA7.phar. Reason:
<pre> Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>
</body>
</html>
[PMS] Server stopped.
navigate_next
</pre>
    
and i went to https://jenkins.pmmp.io/job/PocketMine-MP/ and i didnt found pmmp build #315

### OS:

Windows

### PHP Version:

7.0.3

**Comment by Ad5001** [comment]
Ok looks like build 315 was deleted. I will update the app with the new PHP installer & pmmp phar

**Comment by r7vmc** [comment]
@Ad5001 ok thanks for solving the problem

**Comment by Ad5001** [comment]
It is not solved yet. I'll close the issue when I'll have done the update.

**Comment by r7vmc** [comment]
@Ad5001 ok

**Comment by Ad5001** [comment]
Temp fix has been provided. You should be able to recreate the server with a correct phar.

**Comment by r7vmc** [comment]
versions.json didn't update it self in my computer even after creating new server and restart the program so I had to update manually from http://psm.mcpe.fun/versions.json
and it's still pointing to the old build url

**Comment by Ad5001** [comment]
That's interesting... It should update himself at startup. I'll create an another issue for this.
