### ISSUE TITLE
1.2 phars, downloaded file isn't complete.

### ISSUE THREAD

**Issue by r7vmc** [pmt-mcpe-fun/PocketMineServerManager#3]
## Description:    

when i launch the server i get this error

failed to open stream: phar "/home/r7vmc/.pocketmine/servers/test/PocketMine-MP.phar" has a broken signature in /home/r7vmc/.pocketmine/servers/test/PocketMine-MP.phar on line 1

i didnt change the .phar file

### OS:

Linux

### PHP Version:

7.0.3
    
    
### Steps to reproduce:

1. ...
2. ...
3. ...

**Comment by Ad5001** [comment]
Ok. What version did you try downloading? Was the server created before the update? If so, could you send me your "PocketMine-MP.phar" file (when you're on the server page, click "open server folder").

**Comment by r7vmc** [comment]
i used the default 1.2 phar and i changed it and everything working fine now

**Comment by Ad5001** [comment]
Do you have a copy of that phar which bugged? Does it happend again when you create a new server?

**Comment by r7vmc** [comment]
yes it does happen when i create new server

**Comment by r7vmc** [comment]
https://expirebox.com/download/b71c653f8c5bc0d2b233e486d7007039.html and this is the phar

**Comment by Ad5001** [comment]
Ok I looked into this and it looks like the file wasn't downloaded completely. Have you got connection issue sometimes?

Temporary work around: delete ~/.cache/PSM, restart the app, and recreate a server.

**Comment by r7vmc** [comment]
No I don't

**Comment by Ad5001** [comment]
Ok...
Is PSM on a VPS? A laptop? A desktop computer? (this may be causing connection issues.)

**Comment by r7vmc** [comment]
Laptop And Connected With Ethernet Cable

**Comment by Ad5001** [comment]
I'll have to test it on few different machines on my side.

Btw, have you tried deleting the ~/cache/PSM folder to see if this bug happends again?

**Comment by r7vmc** [comment]
I'm gonna try

**Comment by ghost** [comment]
Bump
