### ISSUE TITLE
.apk (android)

### ISSUE THREAD

**Issue by ghost** [pmt-mcpe-fun/PocketMineServerManager#4]
## Description:     

### Steps to reproduce:  2. ...we can download the application but have can not install it ![screenshot_2017-10-25-02-03-28](https://user-images.githubusercontent.com/25569806/31973987-3d0ebe52-b929-11e7-86a3-c68d9fb1e9ff.png) `There was a problem parsing the package`

**Comment by Ad5001** [comment]
I should really remove the apk. It was a test and : https://github.com/electron/electron/issues/562. You can use PSM thought [termux](https://termux.com/) on an android device.

**Comment by armagadon159753** [comment]
of course then in this case it is useless. thank you for the information.
