### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by llronaldoll** [pmt-mcpe-fun/PocketMineServerManager#5]
I get error when starting the program, and also when starting the server!
![erropms](https://user-images.githubusercontent.com/5334591/34703112-5c942ee8-f4d8-11e7-904c-1767beb67735.png)
![pms2](https://user-images.githubusercontent.com/5334591/34703113-5cb334dc-f4d8-11e7-80a3-4756e616f716.png)

**Comment by Ad5001** [comment]
Ok. Check your .pocketmine/php/bin/ and tell me everything you have inside of it.

**Comment by llronaldoll** [comment]
![pmsm](https://user-images.githubusercontent.com/5334591/34722616-b4f3ed52-f52e-11e7-954d-3d006d9d8df4.png)
now have, this spam on console

**Comment by Ad5001** [comment]
Ok. Looks like the PSMCore plugin's missing... you could either recreate a server and the PSMCore plugin will be redownloaded or download the latest version from http://psm.mcpe.fun/download/PSMCore/ corresponding to  your version.

**Comment by llronaldoll** [comment]
now work, thanks friend!. update for pt-br lang please !
