### ISSUE TITLE
Irrelivant Issue

### ISSUE THREAD

**Issue by llronaldoll** [pmt-mcpe-fun/PocketMineServerManager#6]
:octocat: This issue has marked as *spam* by a contributor or owner, it has been closed, and locked. The original contents of this issue have been saved and can be reviewed by contributors [here](https://spammer-bot.github.io).

**Comment by Ad5001** [comment]
I haven't put a language option, yet. I'm pretty busy so I don't have the time yet to do this. I'll add it to the next release

**Comment by Ad5001** [comment]
Uhh wtf @nathfreder ?

**Comment by ghost** [comment]
@Ad5001 Sorry about that, I tested on the wrong repository

**Comment by Ad5001** [comment]
Can you revert this then?

**Comment by ghost** [comment]
@Ad5001 No, hmmm..

**Comment by ghost** [comment]
Again, sorry about this.
