### ISSUE TITLE
RestartMe plugin not working on PSM

### ISSUE THREAD

**Issue by Atoman03** [pmt-mcpe-fun/PocketMineServerManager#8]
## Description:    

    I have uploaded the plugin and ran the server. When it was time it shut down then it didn't turn back on.

### OS:

Ubuntu 16.04

### PHP Version:

7.0.3
    
    
### Steps to reproduce:

1. Upload RestartMe phar to server
2. Then wait till it shuts down

**Comment by Ad5001** [comment]
I understand why and fixing it would require a major architectural change, wich would unoptimap for the people. I'll add fork RestartMe to make a fixed version.

**Comment by Atoman03** [comment]
Ok

**Comment by Atoman03** [comment]
Could you send me the link to the fork of RestartMe?

**Comment by Ad5001** [comment]
Sorry I didn't make it yet. Just wondering, doesn't the server auto restart when it crash by default?

**Comment by Atoman03** [comment]
What do you mean? When it overloads or something it would just stop, it wouldn't reload. In the normal version, like if I ran the start.sh and the loop was on then yes but with PSM it doesn't come with the start.sh loop function.

**Comment by Ad5001** [comment]
I made a commit which added a settings (when you "edit server.properties") to make a start loop. Try downloading the upstream branch (`git clone https://github.com/pmt-mcpe-fun/server-manager` with git), run `npm install` and then `npm run`.
When you'll edit your server, you'll see the new toggle in the "Edit sever.properties" menu.

**Comment by Atoman03** [comment]
Nice, thanks

**Comment by Atoman03** [comment]
Do I have to uninstall PSM then do that?

**Comment by Atoman03** [comment]
I tried to install and it says that the electron failed on my system.

**Comment by Ad5001** [comment]
>Do I have to uninstall PSM then do that?
No you don't have too uninstall it.
> I tried to install and it says that the electron failed on my system.
Can you send me the error message please?

**Comment by Atoman03** [comment]
This is what it did:
`adam@adam-Dell-XPS420:~/server-manager$ npm install
loadDep:uuid → addNamed   ▌ ╢██████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"4.2.6","np
> electron@1.8.4 postinstall /home/adam/server-manager/node_modules/electron
> node install.js

sh: 1: node: not found
pocketmine-server-manager@1.1.1 /home/adam/server-manager
├── daemon-plus@1.1.2  (git+https://github.com/minecraft-tools/daemon-plus.git#16e2dae36a425602e41d4ca4af4159a5e274fed6)
├── electron-require@0.3.0 
├─┬ js-yaml@3.11.0 
│ ├─┬ argparse@1.0.10 
│ │ └── sprintf-js@1.0.3 
│ └── esprima@4.0.0 
├─┬ material-components-web@0.14.0 
│ ├── @material/animation@0.2.3 
│ ├── @material/auto-init@0.1.4 
│ ├── @material/base@0.2.6 
│ ├─┬ @material/button@0.3.11 
│ │ ├─┬ @material/ripple@0.8.8 
│ │ │ └── @material/theme@0.4.0 
│ │ └── @material/typography@0.3.0 
│ ├─┬ @material/card@0.2.10 
│ │ ├── @material/rtl@0.1.8 
│ │ ├── @material/theme@0.4.0 
│ │ └── @material/typography@0.3.0 
│ ├── @material/checkbox@0.3.7 
│ ├─┬ @material/dialog@0.3.5 
│ │ ├── @material/animation@0.3.1 
│ │ ├─┬ @material/ripple@0.8.8 
│ │ │ └── @material/theme@0.4.0 
│ │ ├── @material/typography@0.1.1 
│ │ └─┬ focus-trap@2.4.3 
│ │   └── tabbable@1.1.2 
│ ├─┬ @material/drawer@0.5.9 
│ │ ├── @material/animation@0.4.1 
│ │ ├── @material/theme@0.4.0 
│ │ └── @material/typography@0.3.0 
│ ├─┬ @material/elevation@0.1.13 
│ │ └── @material/animation@0.4.1 
│ ├─┬ @material/fab@0.3.16 
│ │ ├── @material/animation@0.3.1 
│ │ ├─┬ @material/ripple@0.8.8 
│ │ │ └── @material/theme@0.4.0 
│ │ └── @material/theme@0.2.0 
│ ├─┬ @material/form-field@0.2.17 
│ │ ├─┬ @material/selection-control@0.1.3 
│ │ │ └─┬ @material/ripple@0.8.8 
│ │ │   └── @material/theme@0.4.0 
│ │ ├── @material/theme@0.4.0 
│ │ └── @material/typography@0.3.0 
│ ├─┬ @material/grid-list@0.2.13 
│ │ ├── @material/theme@0.4.0 
│ │ └── @material/typography@0.3.0 
│ ├─┬ @material/icon-toggle@0.1.22 
│ │ ├── @material/animation@0.4.1 
│ │ ├── @material/ripple@0.8.8 
│ │ └── @material/theme@0.4.0 
│ ├── @material/layout-grid@0.3.0 
│ ├─┬ @material/linear-progress@0.1.11 
│ │ ├── @material/animation@0.4.1 
│ │ └── @material/theme@0.4.0 
│ ├─┬ @material/list@0.2.20 
│ │ ├── @material/ripple@0.8.8 
│ │ ├── @material/theme@0.4.0 
│ │ └── @material/typography@0.3.0 
│ ├─┬ @material/menu@0.4.8 
│ │ ├── @material/animation@0.4.1 
│ │ ├── @material/theme@0.4.0 
│ │ └── @material/typography@0.3.0 
│ ├─┬ @material/radio@0.2.15 
│ │ ├── @material/animation@0.4.1 
│ │ ├── @material/ripple@0.8.8 
│ │ └── @material/theme@0.4.0 
│ ├── @material/ripple@0.7.0 
│ ├─┬ @material/select@0.3.18 
│ │ ├── @material/animation@0.4.1 
│ │ ├── @material/theme@0.4.0 
│ │ └── @material/typography@0.3.0 
│ ├── @material/slider@0.1.1 
│ ├── @material/snackbar@0.2.2 
│ ├─┬ @material/switch@0.1.15 
│ │ ├── @material/animation@0.4.1 
│ │ └── @material/theme@0.4.0 
│ ├─┬ @material/tabs@0.2.9 
│ │ ├── @material/animation@0.3.1 
│ │ ├─┬ @material/ripple@0.8.8 
│ │ │ └── @material/theme@0.4.0 
│ │ ├── @material/theme@0.3.1 
│ │ └── @material/typography@0.3.0 
│ ├─┬ @material/textfield@0.3.6 
│ │ ├── @material/animation@0.3.1 
│ │ ├─┬ @material/ripple@0.8.8 
│ │ │ └── @material/theme@0.4.0 
│ │ ├── @material/theme@0.2.0 
│ │ └── @material/typography@0.3.0 
│ ├── @material/theme@0.1.7 
│ ├─┬ @material/toolbar@0.4.11 
│ │ ├── @material/theme@0.4.0 
│ │ └── @material/typography@0.3.0 
│ └── @material/typography@0.2.3 
└─┬ node-notifier@5.2.1 
  ├── growly@1.3.0 
  ├── semver@5.5.0 
  ├── shellwords@0.1.1 
  └─┬ which@1.3.0 
    └── isexe@2.0.0 

npm ERR! Linux 4.13.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron@1.8.4 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron@1.8.4 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/adam/server-manager/npm-debug.log
`
Then the npm-debug is here: 
[npm-debug.log](https://github.com/pmt-mcpe-fun/server-manager/files/1896137/npm-debug.log)

**Comment by Ad5001** [comment]
Ok try running `node` in your terminal. It looks like the shortcut doesn't exist (try updating node & npm as it seems a bit outdated).
Otherwise, try running the following command and re run `npm install`:
`alias node=nodejs`

**Comment by Atoman03** [comment]
I forgot to install nodejs, sorry.
Works now
Where would the newest PSMCore plugin be?

**Comment by Ad5001** [comment]
You don't need to update the integration plugin for this, it's directly bundled in the app :) You just have to enable it in the "Edit servers.properties" and enable start loop.

**Comment by Atoman03** [comment]
Ok, thank you
